# Dockerfile.dev
FROM python:3.10

# Set the working directory inside the container
WORKDIR /app

# Upgrade pip to the latest version
RUN pip install --upgrade pip

# Copy the requirements.txt file into the container
COPY requirements.txt requirements.txt

# Install the dependencies specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container
COPY . .

# Expose the port that Django's development server will run on
EXPOSE 8000

# Set environment variable for development mode
ENV DEBUG=True

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
