version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev  # Use Dockerfile.dev for development
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
